### ISSUE TITLE
Server compatibility while generating token

### ISSUE THREAD

**Issue by mateuszgwozdz** [hugodias/cakegallery#3]
Hey,

I had a problem while uploading photos something was breaking, after some debuggin I found that my server is not compatible with some functions running when generating token in Component/UtilComponent.php

What I've done to fix this is change the crypto_rand_secure($min, $max) to:

    public function crypto_rand_secure($min, $max)
    {
        return md5(uniqid(mt_rand(), true));
    }

**Comment by hugodias** [comment]
Fixed in commit a53b43c041f59452f0ff55cc63d9785c0724bbad
