### ISSUE TITLE
Undefined index: Picture

### ISSUE THREAD

**Issue by Zwaen91** [hugodias/cakegallery#5]
In the following files:
APP/Plugin/Gallery/Controller/AlbumsController.php, line 57
APP/Plugin/Gallery/View/Albums/upload.ctp, line 192

If you upload database entries and images are uploaded but the view doesn't show them.

**Comment by hugodias** [comment]
If your database relationship is correct this should return an empty array and not an Undefined error, as you can see here: https://www.dropbox.com/s/gqltbill6myjbxo/Screenshot%202015-01-12%2010.53.00.png?dl=0
