### ISSUE TITLE
URL barra invertida

### ISSUE THREAD

**Issue by FredericoSFerreira** [hugodias/cakegallery#6]
problema e na URL das imagens esta com as barras invertidas desse modo a mesma nao e renderizada na view ficando
/teste/files\gallery\1\medium-F8S3MTHeSLNijD1OneEiQc2xzx5YW1Oc.jpg﻿
tando para as imagens quanto para os albuns

**Comment by hugodias** [comment]
@FredericoSFerreira esse erro acontece quando você utiliza algum helper? Você está utilizando essa plugin em qual SO? Windows? 

Tenho uma leve impressão que o erro está aqui: https://github.com/hugodias/cakegallery/blob/master/Model/Picture.php#L482

Esta linha é responsável por criar o path das imagens e salvar no banco.

Por favor, verifique se no banco de dados o caminho já está com as barras invertidas

**Comment by FredericoSFerreira** [comment]
Fiz o teste um uma instalação limpa do cake SO windows

**Comment by FredericoSFerreira** [comment]
Corrigi adicionando: return WWW_ROOT . '/files' . '/' . 'gallery/'  . $album_id . '/'. $filename;

**Comment by hugodias** [comment]
Pois é, vi aqui na documentação do Cakephp que o DS funciona como `\` no windows, em vez de `/`. http://book.cakephp.org/2.0/en/core-libraries/global-constants-and-functions.html

Vou ver possíveis impactos e corrigir isso. Obrigado @FredericoSFerreira

**Comment by hugodias** [comment]
Usuários de windows com problemas favor utilizar a seguinte solução: http://stackoverflow.com/a/4095765/708385

É preferível o próprio usuário alterar o código na aplicação que esteja hospedando o plugin do que alterar o próprio código do plugin. Porque em caso de atualização da versão do plugin é possível que esta modificação seja perdida.

Vou criar um Help mostrando essa dica

**Comment by hugodias** [comment]
Adiconada: https://github.com/hugodias/cakegallery/commit/34e93346f5d5f7b4c5e199a5fe7ac00278853567
